{{- $configGenerator := dict
"config" .Values.injectedEnv
"root" $
"commonLabels" .Values.commonLabels
"name" (tpl .Values.fullName .) }}

{{- include "common.config.resources-with-injected-env" $configGenerator}}
