{{- if gt (len .Values.ingress.hosts) 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.fullName . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod-traefik
    {{- $middlewares := .Values.ingress.middlewares }}

    {{- if .Values.sablier.enabled }}
    {{- $middlewares = append $middlewares (tpl .Values.sablier.traefikMiddleware .) }}
    {{- end }}

    {{- if $middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $middlewares }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ tpl $.Values.fullName $ }}
                port:
                  name: http
  {{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . }}
      secretName: {{ printf "%s-tls" . }}
  {{- end }}
{{- end }}
